// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAN41HYHixjeDVUzJqSetNgQZ2hQRPpplI',
    appId: '1:337488247760:web:16f02a0c93cad1b09197d5',
    messagingSenderId: '337488247760',
    projectId: 'osp-kolumna',
    authDomain: 'osp-kolumna.firebaseapp.com',
    storageBucket: 'osp-kolumna.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAN41HYHixjeDVUzJqSetNgQZ2hQRPpplI',
    appId: '1:337488247760:android:16f02a0c93cad1b09197d5',
    messagingSenderId: '337488247760',
    projectId: 'osp-kolumna',
    storageBucket: 'osp-kolumna.firebasestorage.app',
    androidClientId: '337488247760-dummy.apps.googleusercontent.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAN41HYHixjeDVUzJqSetNgQZ2hQRPpplI',
    appId: '1:337488247760:ios:16f02a0c93cad1b09197d5',
    messagingSenderId: '337488247760',
    projectId: 'osp-kolumna',
    storageBucket: 'osp-kolumna.firebasestorage.app',
    iosBundleId: 'pl.ospkolumna.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAN41HYHixjeDVUzJqSetNgQZ2hQRPpplI',
    appId: '1:337488247760:macos:16f02a0c93cad1b09197d5',
    messagingSenderId: '337488247760',
    projectId: 'osp-kolumna',
    storageBucket: 'osp-kolumna.firebasestorage.app',
    iosBundleId: 'pl.ospkolumna.app',
  );
}
